memory_limit = 512M
upload_max_filesize = 50M
post_max_size = 55M
max_execution_time = 60
expose_php = Off
date.timezone = UTC

opcache.enable = 1
opcache.validate_timestamps = 1
opcache.memory_consumption = 256
